Added Erecto Spell
championballer/spellcmds pull request #52
Opened 2019-10-11 04:27 UTC by sun-fox

It creates a new file, straight-up at that location.

2019-10-11 06:33 UTC, championballer requested changes
Please resolve the required conflicts. Thanks.

2019-10-14 03:14 UTC, championballer submitted a review, later dismissed

2019-10-14 03:15 UTC, championballer reviewed
There are still conflicts @sun-fox . Can't do an automatic verified merge.

2019-10-14 17:43 UTC, sun-fox commented
I have made changes accordingly to the file but still find resolve conflicts, please help!

2019-10-20 11:39 UTC, championballer approved these changes

2019-10-20 11:40 UTC, closed without merging